### ISSUE TITLE
Npm install error on v1.5.2, even after Hyper reinstall via Homebrew

### ISSUE THREAD

**Issue by devilleweppenaar** [dfrankland/hyper-sync-settings#17]
Unfortunately the latest release (v1.5.2) doesn't seem like it has resolved all the issues.

I'm using Node Borom (v6.9.1) via nvm.

Here is the npm output:
```
$ npm i
npm WARN deprecated hyperterm-tab-icons@1.1.0: hyperterm-tab-icons renamed to hyper-tab-icons

> nodegit@0.15.1 preinstall /Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52/vendor/libssh2/configure --with-libssl-prefix=/Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52/vendor/libssh2/configure --with-libssl-prefix=/Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52/vendor/openssl/openssl' }
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52/vendor/libssh2/configure --with-libssl-prefix=/Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52/vendor/libssh2/configure --with-libssl-prefix=/Users/devillex/.hyper_plugins/node_modules/.staging/nodegit-e4435c52/vendor/openssl/openssl' }
hyper-plugins@0.0.1 /Users/devillex/.hyper_plugins
├── d@0.1.1  extraneous
├── hypercwd@0.1.6 
├─┬ hyperline@0.6.0 
│ ├─┬ color@0.11.4 
│ │ ├── clone@1.0.2 
│ │ ├─┬ color-convert@1.6.0 
│ │ │ └── color-name@1.1.1 
│ │ └── color-string@0.3.0 
│ ├── json-loader@0.5.4 
│ └── systeminformation@3.8.1 
├── hyperterm-atom-dark@1.1.2 
├─┬ hyperterm-lastpass@1.0.1 
│ ├─┬ babel-polyfill@6.16.0 
│ │ ├── core-js@2.4.1 
│ │ └── regenerator-runtime@0.9.6 
│ ├── babel-runtime@6.18.0 
│ ├─┬ bootstrap@4.0.0-alpha.5 
│ │ ├── jquery@3.1.1 
│ │ └── tether@1.3.7 
│ ├── fuzzaldrin@2.1.0 
│ ├─┬ lastpass@1.0.2 
│ │ ├── bluebird@3.4.6 
│ │ ├── es6-error@3.2.0 
│ │ ├─┬ form-data@1.0.1 
│ │ │ ├─┬ async@2.1.2 
│ │ │ │ └── lodash@4.16.6 
│ │ │ ├─┬ combined-stream@1.0.5 
│ │ │ │ └── delayed-stream@1.0.0 
│ │ │ └─┬ mime-types@2.1.12 
│ │ │   └── mime-db@1.24.0 
│ │ ├─┬ html-to-text@2.1.3 
│ │ │ ├── he@1.1.0 
│ │ │ ├── htmlparser@1.7.7 
│ │ │ ├─┬ optimist@0.6.1 
│ │ │ │ ├── minimist@0.0.10 
│ │ │ │ └── wordwrap@0.0.3 
│ │ │ ├── underscore@1.8.3 
│ │ │ └─┬ underscore.string@3.3.4 
│ │ │   ├── sprintf-js@1.0.3 
│ │ │   └── util-deprecate@1.0.2 
│ │ ├─┬ node-fetch@1.6.3 
│ │ │ ├─┬ encoding@0.1.12 
│ │ │ │ └── iconv-lite@0.4.13 
│ │ │ └── is-stream@1.1.0 
│ │ ├─┬ sanitize-filename@1.6.1 
│ │ │ └─┬ truncate-utf8-bytes@1.0.2 
│ │ │   └── utf8-byte-length@1.0.4 
│ │ └─┬ xml2js@0.4.17 
│ │   ├── sax@1.2.1 
│ │   └── xmlbuilder@4.2.1 
│ ├─┬ react@15.3.2 
│ │ ├─┬ fbjs@0.8.5 
│ │ │ ├── core-js@1.2.7 
│ │ │ ├── immutable@3.8.1 
│ │ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ │ └── whatwg-fetch@1.0.0 
│ │ │ ├─┬ promise@7.1.1 
│ │ │ │ └── asap@2.0.5 
│ │ │ └── ua-parser-js@0.7.11 
│ │ ├─┬ loose-envify@1.3.0 
│ │ │ └── js-tokens@2.0.0 
│ │ └── object-assign@4.1.0 
│ └── react-dom@15.3.2 
├── hyperterm-tab-icons@1.1.0 
└─┬ hyperterm-tabs@1.2.1 
  └── classnames@2.2.5 

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/devillex/.nvm/versions/node/v6.9.1/bin/node" "/Users/devillex/.nvm/versions/node/v6.9.1/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.15.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.15.1 preinstall script 'node lifecycleScripts/preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/devillex/.hyper_plugins/npm-debug.log
```

Please let me know if you require more information.

**Comment by dfrankland** [comment]
Hey there! Thank you for reporting this issue.

For `hyper-sync-settings`  to be installable again this PR on Hyper must be merged: https://github.com/zeit/hyper/pull/970

Also, from your error log I can see that you may be still trying to install `hyperterm-sync-settings` (which is deprecated at version 1.5.1),  not the updated `hyper-sync-settings` (starts at version 1.5.2).

**Comment by devilleweppenaar** [comment]
Hi @dfrankland! Thanks for the prompt response. That makes a lot of sense! Thought I got all of the renames, but apparently not 🙈. I've subscribed to the hyper PR and will test again when it's merged.

**Comment by dfrankland** [comment]
https://github.com/zeit/hyper/pull/970 is now merged so we should see this fixed when [Hyper.app version 0.8.4](https://github.com/zeit/hyper/releases/tag/0.8.4) is released.

**Comment by devilleweppenaar** [comment]
Awesome, thanks for the update!

**Comment by dfrankland** [comment]
This should work now that Hyper v1.0.0 is released: https://github.com/zeit/hyper/releases/tag/1.0.0
