### ISSUE TITLE
Plugin error!

### ISSUE THREAD

**Issue by ianwalter** [dfrankland/hyper-sync-settings#8]
I got something like the following notification from Hyperterm:

```
Plugin error!
hyperterm-sync-settings did not load (Module failed to self-register)
```

The plugin worked initially but seems to no longer backup settings.
No notification is given after a failed backup.

**Comment by ianwalter** [comment]
Also getting the following error when trying to click on a menu option within the "Open" menu:

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at EventEmitter.webContents.executeJavaScript (/Applications/HyperTerm.app/Contents/Resources/electron.asar/browser/api/web-contents.js:145:32)
    at runJs (/Users/ian/.hyperterm_plugins/node_modules/hyperterm-sync-settings/lib/getOpen.js:7:17)
    at Object.window (/Users/ian/.hyperterm_plugins/node_modules/hyperterm-sync-settings/lib/getOpen.js:11:20)
    at click (/Users/ian/.hyperterm_plugins/node_modules/hyperterm-sync-settings/index.js:88:26)
    at MenuItem.click (/Applications/HyperTerm.app/Contents/Resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/Applications/HyperTerm.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
```

**Comment by ianwalter** [comment]
Restarting Hyperterm fixed the second error and now I get an error notification when trying to backup: `Cannot push non-fastforwardable reference`

**Comment by dfrankland** [comment]
That's a `git` problem. Make a quick copy of your `~/.hyperterm.js`. Restore using the `Restore Settings` command (this will download from your gist and `fastforward` your local repo, but resets your settings to a previous commit). Then copy back your `~/.hyperterm.js` file. Finally, using the `Backup Settings` command to backup your settings.

**Comment by ianwalter** [comment]
Thanks, that fixed the second error. I'll see if I can reproduce the first.

**Comment by dfrankland** [comment]
I've seen that first error happen every so often. Still not sure what exactly is causing it :/

**Comment by ianwalter** [comment]
@dfrankland actually, for the `Cannot push non-fastforwardable reference`, why doesn't the plugin just do a git pull before backing up? I realize it can result in merge conflicts, but if there are conflicts, it won't allow the user to backup anyway, and it will at least auto-merge some of the time.

**Comment by dfrankland** [comment]
Not a bad idea! We should catch that error and display a notification of it. In the notification it would prompt to click on it to do a quick `git pull`.

**Comment by ianwalter** [comment]
The original error has something to do with electron, nodegit, and possibly node version. I tried rebuilding these, but it didn't fix the problem. What does specifying the electron in engines section of NPM do?

**Comment by ianwalter** [comment]
Here's the error in devtools when I click View > Reload:

```
bundle.js:1 Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ian/.hyperterm_plugins/node_modules/hyperterm-sync-settings/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)(anonymous function) @ bundle.js:1P @ bundle.js:1reload @ bundle.js:1(anonymous function) @ bundle.js:6emitOne @ events.js:96emit @ events.js:188value @ bundle.js:6emitTwo @ events.js:106emit @ events.js:191
bundle.js:6 [Notification] Plugin load error: "hyperterm-sync-settings" failed to load in the renderer process. Check Developer Tools for details.
```

**Comment by dfrankland** [comment]
Are you on macOS Sierra?

**Comment by ianwalter** [comment]
Yes, although I was having this problem (it could have been a different problem under the hood I guess) before I upgraded.

**Comment by dfrankland** [comment]
This will probably be fixed with [this PR](https://github.com/zeit/hyper/pull/970) and the next release. For now, I'll close this, but if you run into another problem feel free to open another issue.
